name: Microservice Cotract Check

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: "Pull Request Number"
        required: true
      branch:
        description: "Branch Name"
        required: true

jobs:
  contract-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Start User Service
        run: docker compose up -d --build user-service

      - name: Wait for Service
        run: sleep 5

      - name: Run Contract Test
        run: docker compose up --build --abort-on-container-exit --exit-code-from contract-test contract-test

      - name: Cleanup
        if: always()
        run: docker compose down

